name: Test Compilation

on: 
 push:
  branches:
   - master

jobs:

 make:

  name: Run-make

  runs-on: ubuntu-latest

  steps:

   - uses: actions/checkout@v1

   - name: update system
     run: sudo apt update

   - name: install dependencies
     run: sudo apt install libsdl2-2.0-0 libsdl2-dev -y

   - name: run make 
     run: |
      cd code
      make
