name: Test Compilation

on: 
 push:
  branches:
   - master

jobs:
 make:
  name: Run-make
   runs-on: ubuntu-latest
     steps:
      - run: apt install libsdl2.0
      - run: cd code
      - run: make
