name: Test Compilation

on: 
 push:
  branches:
   - master

jobs:

 make:

  name: Run-make

  runs-on: ubuntu-latest

  steps:

   - uses: actions/checkout@v1

   - name: setup compilation
     run: sudo apt install libsdl2-dev && cd code

   - name: run compilation
     run: make
